name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      
      - name: Install dependencies
        run: yarn
      
      - name: Lint
        run: yarn lint
      
      - name: Test
        run: yarn test
      
      - name: Set API key
        shell: bash
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        run: yarn build
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
